<?xml version="1.0" encoding="UTF-8"?>
<integrity name="Integrity JUnit Testing" timestamp="06.03.15 09:25" isotimestamp="2015-03-06T09:25:04" duration="10.149" abortMessage="This is an abort exception in a tabletest">
  <variables />
  <suite id="0" name="integrity.basic.exceptions.abortExceptions.abortExceptionInTableTestNestedWithMoreStuffBehind" timestamp="06.03.15 09:25:04.0490">
    <setup />
    <variables />
    <statements>
      <suite id="1" line="53" name="integrity.basic.exceptions.abortExceptions.innerAbortExceptionInTableTestNestedWithMoreStuffBehind" timestamp="06.03.15 09:25:04.0490">
        <setup />
        <variables />
        <statements>
          <call id="2" line="58" name="noOp" description="Do absolutely nothing." fixture="de.gebit.integrity.tests.fixtures.basic.NoOpFixture#noOp" timestamp="06.03.15 09:25:04.0490">
            <parameters />
            <result duration="0.081" type="success" />
          </call>
          <tabletest id="3" line="59" name="throwAbortExceptionTest" description="Throws an abortion exception" fixture="de.gebit.integrity.tests.fixtures.basic.NoOpFixture#throwAbortException" timestamp="06.03.15 09:25:04.0506">
            <results duration="4.513" successCount="0" failureCount="0" exceptionCount="1">
              <result duration="1.033" description="Throws an abortion exception" type="exception" exceptionMessage="This is an abort exception in a tabletest" exceptionTrace="de.gebit.integrity.exceptions.AbortExecutionException: This is an abort exception in a tabletest&#xD;&#xA;&#x9;at de.gebit.integrity.tests.fixtures.basic.NoOpFixture.throwAbortException(NoOpFixture.java:181)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:597)&#xD;&#xA;&#x9;at de.gebit.integrity.fixtures.FixtureWrapper.execute(FixtureWrapper.java:283)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeTableTest(DefaultTestRunner.java:1364)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:957)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:757)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.callSuite(DefaultTestRunner.java:657)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:949)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:757)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.runInternal(DefaultTestRunner.java:608)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:498)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:433)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.IntegrityJUnitTest.executeIntegritySuite(IntegrityJUnitTest.java:99)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.basic.exceptions.AbortExceptions.abortExceptionInTableTestNestedWithMoreStuffBehind(AbortExceptions.java:112)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:597)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#xD;&#xA;&#x9;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#xD;&#xA;&#x9;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#xD;&#xA;">
                <parameters>
                  <parameter name="message" value="This is an abort exception in a tabletest" />
                </parameters>
              </result>
            </results>
          </tabletest>
        </statements>
        <teardown />
        <result duration="8.633" successCount="0" failureCount="0" exceptionCount="1" testExceptionCount="1" callExceptionCount="0" />
      </suite>
    </statements>
    <teardown />
    <result duration="9.150" successCount="0" failureCount="0" exceptionCount="1" testExceptionCount="1" callExceptionCount="0" />
  </suite>
</integrity>

